### ISSUE TITLE
Add URIParser integration back in

### ISSUE THREAD

**Issue by davidanthoff** [rofinn/FilePaths.jl#18]
Would you be open to put the URIParser integration back in? It seems a really lightweight dependency, and my main use case for FilePaths is actually a really smooth conversion between file paths and URIs, so it would be great if we could just support that out of the box.

I'd be happy to do the PR that adds it back in.

**Comment by rofinn** [comment]
My reasoning for dropping it is:

1. I'd like to see FilePaths.jl in the stdlib once we've flushed out all the details, so I wanted to avoid dependencies on other package is a good idea.
2. I think that functionality makes more sense in URIParser as an optional dependency. Unfortunately, we don't seem to have a performant way of handling optional dependencies [[1]](https://github.com/MikeInnes/Requires.jl/issues/39).
