### ISSUE TITLE
needs new version tagged in Metadata.jl

### ISSUE THREAD

**Issue by catawbasam** [rofinn/FilePaths.jl#3]
julia 0.6 is using an error on @osx_only, which it looks like you've updated on master.  Maybe needs new version tagged in Metadata.jl?

`julia> using FilePaths

WARNING: deprecated syntax "abstract AbstractPath" at C:\Users\x\.julia\v0.6\FilePaths\src\FilePaths.jl:52.
Use "abstract type AbstractPath end" instead.
ERROR: LoadError: LoadError: UndefVarError: @osx_only not defined`

**Comment by rofinn** [comment]
Yeah, I was waiting for a new version of [Humanize](https://github.com/IainNZ/Humanize.jl/issues/7) to be released, but it looks like that's been tagged in METADATA now. Thanks for the reminder though!

**Comment by rofinn** [comment]
Closing now that v0.1.0 has been [merged](https://github.com/JuliaLang/METADATA.jl/pull/9411).
