### ISSUE TITLE
Deprication of `mkpath(x)` to `makedir(x, recursive=true)` does not work if a directory called `x` already exists

### ISSUE THREAD

**Issue by oxinabox** [rofinn/FilePaths.jl#33]
There are 2 differences between `mkdir` and `mkpath`

 1. `mkpath` recursively creates directories
 2. `mkpath` does nothing if the directory already exists, where as `mkdir` throws an error.

The deprecation currently only works for case 1.

**Comment by oxinabox** [comment]
Can this be moved to FilePathsBase.jl?

**Comment by rofinn** [comment]
NOTE: That's what the keyword argument `exist_ok` should be for. I'm starting to be convinced that we should support the exact same API as base in FilePathsBase to minimize confusion and increase the likelihood that it could become a stdlib.
