### ISSUE TITLE
Enhancement: save and load methods for AbstractPaths

### ISSUE THREAD

**Issue by nickrobinson251** [rofinn/FilePaths.jl#34]
Extend FileIO to define the save and load methods for `AbstractPath`s. 

The default behaviour could be to serialize the data to an IOBuffer and call `write(path, bytes)`.

**Comment by rofinn** [comment]
This has been brought up before. https://github.com/rofinn/FilePaths.jl/pull/22#issuecomment-370620375

Unfortunately, we'd need to overload a lot of methods in FileIO for that to work nicely. Also, almost none of the formats we currently use support that interface.

**Comment by nickrobinson251** [comment]
The main benefit of extending `save` and `load` to `AbstractPaths` would be for non-local paths e.g. an `S3Path`, and so we don't have to keep track of when a "filepath" is a `String` or a `*Path`

**Comment by rofinn** [comment]
Right, but we'd need to modify the `File` type in `FileIO` for `save` and `load` to have the same behaviour. I suppose we could opt to only support a subset of the interface.

**Comment by rofinn** [comment]
This is supported as of FileIO 1.3. Unfortunately, many backend file format packages assume filepaths are strings. We'll need to fix each package individually as they come up.
