### ISSUE TITLE
Handling connection information for remote paths

### ISSUE THREAD

**Issue by rofinn** [rofinn/FilePaths.jl#36]
It'd be nice if there was a way to patch code using the filepaths API to use some connection information defined at the outer scope.

# Example

```
# `FTPath` write method
function write(p::FTPath, data, conn::Union{FTPClient, Nothing}=nothing)
    c = conn === nothing ? FTPClient(...) : conn
    ...
end
```

```
# Some function that could even be inside another package
function my_save_func(p::AbstractPath, data)
    ...
    write(p, data)
end
```

```
# User code that want to use an `FTPath` with a connection without directly 
# modifying the call site
...
# Somehow dynamically modify any calls to `read`, `write`, `open` with an `FTPath` to use
# our instance ` c` below. Maybe we could use Cassette.jl to patch those methods?
FTPClient(...) do c
    my_save_func(p"ftp://foo/bar/baz.txt", "Hello World!")
end
```

**Comment by oxinabox** [comment]
We could totally do this, with Cassette I'll code up a demo once I get in.

**Comment by oxinabox** [comment]
## Example code

```
using Cassette

Cassette.@context FtpCtx

struct FTPPath
    path
end


struct FTPClient
    conn
end

function FTPClient(f, conn)
    ctx = FtpCtx(metadata = FTPClient(conn))
    Cassette.recurse(ctx, f)
end

function Cassette.overdub(ctx::FtpCtx, ::typeof(write), p::FTPPath, data)
    conn = ctx.metadata
    write(p, data, conn)
end


function Base.write(p::FTPPath, data, conn::Union{FTPClient, Nothing}=nothing)
    c = conn === nothing ? FTPClient("Default") : conn
    println("Using $(c.conn), wrote $data to $(p.path)")
end


###################################

write(FTPPath("OutsidePath"), "foodata")
write(FTPPath("OutsidePath"), "foodata", FTPClient("Specific"))


function foobar()
    write(FTPPath("InsidePath"), "foodata")
    write(FTPPath("InsidePath"), "foodata", FTPClient("Specific"))
end


FTPClient("Overdubbed") do
    foobar()
end

foobar()
```



## Demo

```
julia> write(FTPPath("OutsidePath"), "foodata")
Using Default, wrote foodata to OutsidePath

julia> write(FTPPath("OutsidePath"), "foodata", FTPClient("Specific"))
Using Specific, wrote foodata to OutsidePath

julia> function foobar()
           write(FTPPath("InsidePath"), "foodata")
           write(FTPPath("InsidePath"), "foodata", FTPClient("Specific"))
       end
foobar (generic function with 1 method)

julia> FTPClient("Overdubbed") do
           foobar()
       end
Using Overdubbed, wrote foodata to InsidePath
Using Specific, wrote foodata to InsidePath

julia> foobar()
Using Default, wrote foodata to InsidePath
Using Specific, wrote foodata to InsidePath
```


Classic dynamic scoping.

Can definately do it, but I am not sure that we should.
I guess it is better than achieving the same via mutating a global ref.

**Comment by rofinn** [comment]
What would be the argument for not doing it? Is there a performance issue or do you just think it makes the code harder to understand?

**Comment by oxinabox** [comment]
I worry it makes code harder to understand.
LIke how is that information getting there?

Most julia code does not use dynamic scoping...

**Comment by rofinn** [comment]
Since we added `S3Path` to AWSS3.jl I think having paths storing the connection information directly seems to work fine. A couple things that were needed for that to work nicely in highly nested chunks of code included:

1. Stale connections should be able to re-establish themselves as the path type shouldn't really need to care about how to manage the connection.
2. Connection information should propagate across various path manipulations (e.g., `parents`, `join`, `walkpath`).
3. High level scripts should construct a base path with the appropriate connection information and pass that to nested functions that only perform connection preserving operations on the path.

I'm gonna close this issue for now as it doesn't currently seem necessary.
