### ISSUE TITLE
Functions `copy`, `remove` and `move` don't exist

### ISSUE THREAD

**Issue by jessymilare** [rofinn/FilePaths.jl#44]
According to README, the functions that copy, remove and move a file are named `copy`, `remove` and `move`, respectively. However, the functions that do those tasks are `cp`, `rm` and `mv`. Either the documentation should be updated or the functions `copy`, `remove` and `move` should be created as aliases to match documentation.

**Comment by rofinn** [comment]
That readme is out of date, as most of the functionality has been moved to [FilePathsBase.jl](https://github.com/rofinn/FilePathsBase.jl). `copy`, `remove` and `move` were deprecated a couple releases ago to better align with the `Base.FIlesystem` API.
