### ISSUE TITLE
Tag a release (for v0.9 for FilePathBase)

### ISSUE THREAD

**Issue by PallHaraldsson** [rofinn/FilePaths.jl#50]
Blocking:
https://github.com/GenieFramework/Genie.jl/issues/269#issuecomment-677452920

**Comment by essenciary** [comment]
> Though I couldn't figure out if Genie needs the extra functionality from FilePaths.jl or if FilePathsBase.jl would suffice and require fewer dependencies.

Good point, I'll give it a try.
