### ISSUE TITLE
Adopt pathlib drive and root structure?

### ISSUE THREAD

**Issue by davidanthoff** [rofinn/FilePaths.jl#8]
I tried to fix things up on Windows, but I'm starting to wonder whether it might make sense to go with the structure of having a drive and a root property of every path, like Python's [pathlib](https://www.python.org/dev/peps/pep-0428/) does. One could then also follow the definition of an anchored path from pathlib, my sense is that to really square the design on Windows and Posix, it would be easier to just follow Python's lead on those things.

In general, I assume pathlib was kind of the model for this package?

**Comment by rofinn** [comment]
Yeah, that was the general idea, but I was probably a bit too biased by the existing filesystem interface in julia. If you're willing to provide a PR for what you had in mind that would be greatly appreciated.

**Comment by davidanthoff** [comment]
Cool, I'll have a go at it.

I'm wondering whether we can copy and translate code from pathlib over here from a licensing point of view. They have a *lot* of code that handles all the corner cases etc. in terms of parsing obscure path formats. I'll ask on the julia slack channel about that.

**Comment by rofinn** [comment]
Yeah, looks like python 3.6 uses a fairly permissive GPL-compatible license, so we probably just need to keep the python ported code in the same file and include the PSF license at the top of it.

**Comment by davidanthoff** [comment]
Yep, that sounds good. Alright, I'll take a stab at root and drive stuff, and fixing things on Windows, except maybe the CPassword fix, that might be easier for you to disable for now?

**Comment by rofinn** [comment]
Alright, I've added a Cpasswd fix and closed #7.
